"""
LexOrch-KG — Agent 7: Explainability Agent
Generates human-interpretable explanations of AI recommendations with confidence breakdowns.
"""

import json
import re
from typing import Any

from langchain.schema import HumanMessage, SystemMessage
from loguru import logger

from app.agents.base_agent import BaseAgent, AgentResult


DISCLAIMER_TEXT = (
    "⚠️ IMPORTANT LEGAL DISCLAIMER: This analysis is generated by an AI system "
    "for decision SUPPORT purposes only. It does NOT constitute legal advice, "
    "a legal opinion, or a judicial decision. The final legal determination "
    "must be made exclusively by qualified human legal professionals including "
    "judges, lawyers, and legal experts. AI-generated analysis may contain "
    "errors, omissions, or biases. Always consult licensed legal professionals "
    "before making any legal decisions."
)

EXPLAINABILITY_SYSTEM = """You are a legal XAI (Explainable AI) specialist.
Your job is to explain WHY an AI system made a specific legal recommendation.

For each explanation, provide:
1. A clear, non-technical explanation of the recommendation
2. The specific evidence that led to this conclusion
3. The legal sections/provisions that apply
4. The precedents that support the reasoning
5. A confidence breakdown (0.0-1.0) for each factor
6. Known limitations and uncertainties

Always include the mandatory disclaimer that this is AI-generated support material.
Write in clear, professional legal language accessible to non-experts."""

EXPLAINABILITY_PROMPT = """Generate a comprehensive explainability report for this legal AI recommendation.

RECOMMENDATION:
{recommendation}

CASE SUMMARY:
{summary}

KEY FACTS USED:
{facts}

LEGAL REASONING:
{reasoning}

EVIDENCE CONSIDERED:
{evidence}

APPLICABLE SECTIONS:
{sections}

PRECEDENTS CITED:
{precedents}

DEBATE OUTCOME:
{debate}

Generate a detailed, transparent explanation of why this recommendation was made.
Return as JSON with keys: explanation, evidence_used, sections_applied, precedents_cited, 
confidence_score, confidence_breakdown, limitations, reasoning_chain"""


class ExplainabilityAgent(BaseAgent):
    """
    Agent 7 — Explainability (XAI)
    
    Generates SHAP-style natural language explanations:
    - Why the recommendation was made
    - What evidence contributed
    - Which legal provisions apply
    - Confidence breakdown per factor
    - Limitations and caveats
    - Mandatory human oversight disclaimer
    """

    def __init__(self) -> None:
        super().__init__("ExplainabilityAgent", step=7)

    async def execute(
        self, state: dict[str, Any]
    ) -> tuple[dict[str, Any], AgentResult]:
        summary = state.get("summary", "")
        key_facts = state.get("key_facts", [])
        reasoning = state.get("legal_reasoning", {})
        debate_result = state.get("debate_result", {})
        entities = state.get("entities", [])
        precedents = state.get("retrieved_precedents", [])

        # Extract final recommendation from debate
        recommendation = debate_result.get("final_recommendation", "")
        if not recommendation:
            recommendation = reasoning.get("preliminary_assessment", "No recommendation generated")

        # Build evidence list
        evidence_list = self._build_evidence_list(key_facts, entities)

        # Extract sections and acts
        sections = [
            e["value"] for e in entities
            if e.get("type") in ("SECTION", "ACT")
        ]

        # Format precedents
        cited_precedents = [
            {"title": p.get("title", "Unknown"), "relevance": p.get("similarity_score", 0)}
            for p in precedents[:5]
        ]

        # Build prompt
        prompt = EXPLAINABILITY_PROMPT.format(
            recommendation=recommendation[:1000],
            summary=summary[:1000],
            facts="\n".join(f"- {f}" for f in key_facts[:8]),
            reasoning=str(reasoning.get("legal_analysis", ""))[:800],
            evidence="\n".join(f"- {e}" for e in evidence_list[:10]),
            sections="\n".join(f"- {s}" for s in sections[:10]) or "None identified",
            precedents="\n".join(f"- {p['title']}" for p in cited_precedents) or "None retrieved",
            debate=f"""
Prosecution confidence: {debate_result.get('prosecution_confidence', 0):.2f}
Defense confidence: {debate_result.get('defense_confidence', 0):.2f}
Consensus: {debate_result.get('consensus', '')[:500]}
""",
        )

        try:
            response = await self.llm.ainvoke([
                SystemMessage(content=EXPLAINABILITY_SYSTEM),
                HumanMessage(content=prompt),
            ])
            tokens_used = getattr(response, "usage_metadata", {}).get("total_tokens", 0)
            explanation_data = self._parse_explanation(response.content)
        except Exception as e:
            logger.error(f"Explainability generation failed: {e}")
            explanation_data = self._default_explanation(recommendation)
            tokens_used = 0

        # Always add the mandatory disclaimer
        explanation_data["disclaimer"] = DISCLAIMER_TEXT

        # Build reasoning chain
        reasoning_chain = self._build_reasoning_chain(
            key_facts, reasoning, debate_result
        )
        explanation_data["reasoning_chain"] = reasoning_chain

        # Override confidence with computed value
        confidence = self._compute_confidence(
            debate_result, reasoning, len(precedents)
        )
        explanation_data["confidence_score"] = confidence

        logger.info(
            f"[ExplainabilityAgent] Generated explanation | "
            f"confidence={confidence:.2f} | "
            f"evidence_items={len(evidence_list)}"
        )

        state["explainability"] = {
            "recommendation": recommendation,
            **explanation_data,
        }

        result = AgentResult(
            agent_name=self.name,
            status="completed",
            output={
                "confidence_score": confidence,
                "evidence_count": len(explanation_data.get("evidence_used", [])),
                "sections_count": len(sections),
                "precedents_count": len(cited_precedents),
                "has_disclaimer": True,
            },
            tokens_used=tokens_used,
        )
        return state, result

    def _build_evidence_list(
        self, facts: list[str], entities: list[dict]
    ) -> list[str]:
        """Compile evidence items from facts and entities."""
        evidence = list(facts[:5])
        for e in entities:
            if e.get("type") == "EVIDENCE":
                evidence.append(e.get("value", ""))
        return [e for e in evidence if e]

    def _parse_explanation(self, text: str) -> dict[str, Any]:
        """Parse JSON explanation from LLM output."""
        try:
            json_match = re.search(r'\{.*\}', text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group())
        except Exception:
            pass

        return {
            "explanation": text[:2000],
            "evidence_used": [],
            "sections_applied": [],
            "precedents_cited": [],
            "confidence_score": 0.5,
            "confidence_breakdown": {},
            "limitations": [
                "Full JSON parsing failed — raw text provided",
                "Manual review recommended",
            ],
        }

    def _default_explanation(self, recommendation: str) -> dict[str, Any]:
        """Fallback explanation when LLM call fails."""
        return {
            "explanation": f"AI Recommendation: {recommendation}. Full explanation generation encountered an error. Please review the raw reasoning and debate outputs.",
            "evidence_used": [],
            "sections_applied": [],
            "precedents_cited": [],
            "confidence_score": 0.3,
            "confidence_breakdown": {"overall": 0.3},
            "limitations": [
                "Explainability agent encountered an error",
                "Manual legal review is essential",
                "Confidence score is conservative due to error",
            ],
        }

    def _build_reasoning_chain(
        self,
        key_facts: list[str],
        reasoning: dict[str, Any],
        debate: dict[str, Any],
    ) -> list[str]:
        """Build a step-by-step reasoning chain for transparency."""
        chain = []

        if key_facts:
            chain.append(f"Step 1: Identified {len(key_facts)} key facts from the document")

        if reasoning.get("legal_analysis"):
            chain.append("Step 2: Applied relevant legal principles and statutes")

        if reasoning.get("precedent_application"):
            chain.append("Step 3: Compared with similar legal precedents")

        if debate.get("prosecution_argument"):
            chain.append("Step 4: Prosecution agent argued the case for conviction/ruling")

        if debate.get("defense_argument"):
            chain.append("Step 5: Defense agent presented counter-arguments")

        if debate.get("judge_assessment"):
            chain.append("Step 6: Neutral judge agent assessed both arguments")

        if debate.get("consensus"):
            chain.append("Step 7: Consensus agent synthesized final recommendation")

        chain.append("Step 8: Explainability agent generated this transparent explanation")

        return chain

    def _compute_confidence(
        self,
        debate: dict[str, Any],
        reasoning: dict[str, Any],
        precedent_count: int,
    ) -> float:
        """
        Compute overall confidence score from multiple factors.
        
        Factors:
        - Debate consensus confidence (40%)
        - Reasoning confidence (30%)
        - Precedent support (20%)
        - Evidence quality (10%)
        """
        debate_conf = debate.get("recommendation_confidence", 0.5) * 0.4
        reasoning_conf = reasoning.get("preliminary_confidence", 0.5) * 0.3
        precedent_conf = min(precedent_count / 10.0, 1.0) * 0.2  # Max at 10 precedents
        evidence_conf = 0.5 * 0.1  # Base evidence quality

        total = debate_conf + reasoning_conf + precedent_conf + evidence_conf
        return round(min(max(total, 0.0), 1.0), 3)
