"""
LexOrch-KG — Agent 8: Report Generation Agent
Generates professional PDF, JSON, and HTML reports using ReportLab.
"""

import json
import os
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from loguru import logger
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    PageBreak,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY

from app.agents.base_agent import BaseAgent, AgentResult
from app.core.config import settings


DISCLAIMER = (
    "LEGAL DISCLAIMER: This report is generated by LexOrch-KG AI Decision Support System "
    "for informational and decision SUPPORT purposes ONLY. It does NOT constitute legal advice, "
    "a legal opinion, or a judicial decision. The final legal determination must be made "
    "exclusively by qualified human legal professionals. AI analysis may contain errors or biases."
)


class ReportAgent(BaseAgent):
    """
    Agent 8 — Report Generation
    
    Generates:
    1. Professional PDF report (ReportLab)
    2. Structured JSON report
    3. HTML report (Jinja2 template)
    """

    def __init__(self) -> None:
        super().__init__("ReportAgent", step=8)
        os.makedirs(settings.reports_dir, exist_ok=True)

    async def execute(
        self, state: dict[str, Any]
    ) -> tuple[dict[str, Any], AgentResult]:
        case_id = str(state["case_id"])
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        base_name = f"report_{case_id[:8]}_{timestamp}"

        reports = {}

        # ── Generate PDF ─────────────────────────────────────────────────────
        pdf_path = os.path.join(settings.reports_dir, f"{base_name}.pdf")
        try:
            self._generate_pdf(pdf_path, state)
            reports["pdf"] = {
                "path": pdf_path,
                "size": os.path.getsize(pdf_path),
            }
            logger.info(f"[ReportAgent] PDF generated: {pdf_path}")
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")

        # ── Generate JSON ─────────────────────────────────────────────────────
        json_path = os.path.join(settings.reports_dir, f"{base_name}.json")
        try:
            json_data = self._generate_json(state)
            with open(json_path, "w", encoding="utf-8") as f:
                json.dump(json_data, f, indent=2, ensure_ascii=False, default=str)
            reports["json"] = {
                "path": json_path,
                "size": os.path.getsize(json_path),
            }
            logger.info(f"[ReportAgent] JSON generated: {json_path}")
        except Exception as e:
            logger.error(f"JSON generation failed: {e}")

        # ── Generate HTML ─────────────────────────────────────────────────────
        html_path = os.path.join(settings.reports_dir, f"{base_name}.html")
        try:
            html_content = self._generate_html(state)
            with open(html_path, "w", encoding="utf-8") as f:
                f.write(html_content)
            reports["html"] = {
                "path": html_path,
                "size": os.path.getsize(html_path),
            }
            logger.info(f"[ReportAgent] HTML generated: {html_path}")
        except Exception as e:
            logger.error(f"HTML generation failed: {e}")

        state["generated_reports"] = reports

        result = AgentResult(
            agent_name=self.name,
            status="completed",
            output={
                "formats_generated": list(reports.keys()),
                "pdf_size": reports.get("pdf", {}).get("size", 0),
                "json_size": reports.get("json", {}).get("size", 0),
                "html_size": reports.get("html", {}).get("size", 0),
            },
        )
        return state, result

    def _generate_pdf(self, path: str, state: dict[str, Any]) -> None:
        """Generate professional PDF report using ReportLab."""
        doc = SimpleDocTemplate(
            path,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            "LexTitle",
            parent=styles["Title"],
            fontSize=20,
            textColor=colors.HexColor("#1e3a5f"),
            spaceAfter=6,
            alignment=TA_CENTER,
        )
        heading_style = ParagraphStyle(
            "LexHeading",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#1e3a5f"),
            spaceAfter=4,
            spaceBefore=12,
        )
        body_style = ParagraphStyle(
            "LexBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            spaceAfter=6,
            alignment=TA_JUSTIFY,
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.red,
            borderColor=colors.red,
            borderWidth=1,
            borderPadding=4,
            backColor=colors.HexColor("#fff3f3"),
        )

        story = []
        explainability = state.get("explainability", {})
        debate = state.get("debate_result", {})
        entities = state.get("entities", [])

        # ── Header ────────────────────────────────────────────────────────────
        story.append(Paragraph("LexOrch-KG", title_style))
        story.append(Paragraph("Legal Decision Support Report", heading_style))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1e3a5f")))
        story.append(Spacer(1, 0.3 * inch))

        # ── Disclaimer ────────────────────────────────────────────────────────
        story.append(Paragraph(DISCLAIMER, disclaimer_style))
        story.append(Spacer(1, 0.2 * inch))

        # ── Case Info ─────────────────────────────────────────────────────────
        story.append(Paragraph("Case Information", heading_style))
        case_data = [
            ["Case ID", str(state.get("case_id", ""))[:36]],
            ["Title", state.get("case_title", "N/A")],
            ["Generated", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")],
            ["Pages", str(state.get("page_count", "N/A"))],
            ["Status", "AI Analysis Complete"],
        ]
        t = Table(case_data, colWidths=[2 * inch, 4 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8eef7")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1e3a5f")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f5f8ff")]),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.2 * inch))

        # ── Summary ───────────────────────────────────────────────────────────
        story.append(Paragraph("Executive Summary", heading_style))
        summary = state.get("summary", "No summary available.")
        story.append(Paragraph(summary[:1500], body_style))
        story.append(Spacer(1, 0.2 * inch))

        # ── Key Facts ─────────────────────────────────────────────────────────
        key_facts = state.get("key_facts", [])
        if key_facts:
            story.append(Paragraph("Key Facts", heading_style))
            for i, fact in enumerate(key_facts[:10], 1):
                story.append(Paragraph(f"{i}. {fact}", body_style))

        # ── AI Recommendation ─────────────────────────────────────────────────
        story.append(PageBreak())
        story.append(Paragraph("AI-Generated Recommendation", heading_style))
        recommendation = explainability.get("recommendation", debate.get("final_recommendation", "N/A"))
        confidence = explainability.get("confidence_score", 0.5)

        rec_data = [
            ["Recommendation", recommendation[:500] if recommendation else "N/A"],
            ["Confidence Score", f"{confidence:.1%}"],
        ]
        t = Table(rec_data, colWidths=[2 * inch, 4 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#fff3cd")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.2 * inch))

        # ── Debate Summary ────────────────────────────────────────────────────
        if debate:
            story.append(Paragraph("Multi-Agent Debate Summary", heading_style))

            if debate.get("prosecution_argument"):
                story.append(Paragraph("Prosecution:", ParagraphStyle("Bold", parent=body_style, fontName="Helvetica-Bold")))
                story.append(Paragraph(debate["prosecution_argument"][:800], body_style))

            if debate.get("defense_argument"):
                story.append(Paragraph("Defense:", ParagraphStyle("Bold", parent=body_style, fontName="Helvetica-Bold")))
                story.append(Paragraph(debate["defense_argument"][:800], body_style))

            if debate.get("judge_assessment"):
                story.append(Paragraph("Judicial Assessment:", ParagraphStyle("Bold", parent=body_style, fontName="Helvetica-Bold")))
                story.append(Paragraph(debate["judge_assessment"][:800], body_style))

        # ── Entities ──────────────────────────────────────────────────────────
        if entities:
            story.append(PageBreak())
            story.append(Paragraph("Extracted Legal Entities", heading_style))
            by_type: dict[str, list] = {}
            for e in entities[:50]:
                etype = e.get("type", "OTHER")
                by_type.setdefault(etype, []).append(e.get("value", ""))

            entity_data = [["Entity Type", "Values"]]
            for etype, values in by_type.items():
                entity_data.append([etype, ", ".join(set(values))[:200]])

            t = Table(entity_data, colWidths=[2 * inch, 4 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f8ff")]),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(t)

        # ── Footer Disclaimer ─────────────────────────────────────────────────
        story.append(Spacer(1, 0.5 * inch))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
        story.append(Paragraph(DISCLAIMER, disclaimer_style))

        doc.build(story)

    def _generate_json(self, state: dict[str, Any]) -> dict[str, Any]:
        """Generate structured JSON report."""
        return {
            "report_metadata": {
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "system": "LexOrch-KG v1.0.0",
                "disclaimer": DISCLAIMER,
            },
            "case": {
                "id": str(state.get("case_id", "")),
                "title": state.get("case_title", ""),
                "file_type": state.get("file_type", ""),
                "page_count": state.get("page_count", 0),
                "word_count": state.get("word_count", 0),
                "ocr_applied": state.get("ocr_applied", False),
            },
            "summary": state.get("summary", ""),
            "key_facts": state.get("key_facts", []),
            "entities": state.get("entities", [])[:50],
            "retrieved_precedents": [
                {
                    "title": p.get("title"),
                    "similarity_score": p.get("similarity_score"),
                    "source": p.get("source"),
                }
                for p in state.get("retrieved_precedents", [])[:10]
            ],
            "legal_reasoning": state.get("legal_reasoning", {}),
            "debate_result": state.get("debate_result", {}),
            "explainability": state.get("explainability", {}),
            "agent_pipeline": [
                {"name": name, "step": i + 1}
                for i, name in enumerate([
                    "CaseUnderstandingAgent",
                    "EntityExtractionAgent",
                    "KnowledgeGraphAgent",
                    "RetrievalAgent",
                    "ReasoningAgent",
                    "DebateAgent",
                    "ExplainabilityAgent",
                    "ReportAgent",
                ])
            ],
        }

    def _generate_html(self, state: dict[str, Any]) -> str:
        """Generate HTML report with inline styling."""
        explainability = state.get("explainability", {})
        debate = state.get("debate_result", {})
        confidence = explainability.get("confidence_score", 0.5)
        conf_color = "#28a745" if confidence > 0.7 else "#ffc107" if confidence > 0.4 else "#dc3545"

        entities_html = ""
        by_type: dict[str, list] = {}
        for e in state.get("entities", [])[:50]:
            by_type.setdefault(e.get("type", "OTHER"), []).append(e.get("value", ""))
        for etype, values in by_type.items():
            entities_html += f'<tr><td><strong>{etype}</strong></td><td>{", ".join(set(values))[:200]}</td></tr>'

        facts_html = "".join(
            f"<li>{f}</li>" for f in state.get("key_facts", [])[:10]
        )

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LexOrch-KG Legal Report — {state.get("case_title", "Case")}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Georgia', serif; background: #f8f9fa; color: #2d3748; line-height: 1.6; }}
  .container {{ max-width: 900px; margin: 40px auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 20px rgba(0,0,0,0.1); }}
  .header {{ background: linear-gradient(135deg, #1e3a5f, #2d6a9f); color: white; padding: 30px; border-radius: 8px 8px 0 0; margin: -40px -40px 30px; text-align: center; }}
  .header h1 {{ font-size: 2em; margin-bottom: 5px; }}
  .header p {{ opacity: 0.85; }}
  .disclaimer {{ background: #fff3f3; border: 1px solid #e53e3e; border-radius: 6px; padding: 15px; margin: 20px 0; color: #c53030; font-size: 0.85em; }}
  h2 {{ color: #1e3a5f; border-bottom: 2px solid #1e3a5f; padding-bottom: 8px; margin: 25px 0 15px; font-size: 1.3em; }}
  .info-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0; }}
  .info-card {{ background: #f0f5ff; border-radius: 6px; padding: 15px; }}
  .info-card label {{ color: #1e3a5f; font-weight: bold; font-size: 0.8em; text-transform: uppercase; }}
  .info-card p {{ font-size: 1em; margin-top: 4px; }}
  .confidence-badge {{ display: inline-block; background: {conf_color}; color: white; padding: 4px 12px; border-radius: 20px; font-size: 0.9em; font-weight: bold; }}
  .debate-section {{ border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 15px 0; }}
  .debate-section h3 {{ color: #1e3a5f; margin-bottom: 10px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
  th {{ background: #1e3a5f; color: white; padding: 10px; text-align: left; font-size: 0.9em; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #e2e8f0; font-size: 0.9em; }}
  tr:nth-child(even) {{ background: #f7fafc; }}
  ul {{ padding-left: 25px; }}
  li {{ margin: 5px 0; }}
  .footer {{ text-align: center; color: #718096; font-size: 0.8em; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>⚖️ LexOrch-KG</h1>
    <p>Legal Decision Support Report</p>
    <p style="font-size:0.9em;margin-top:8px">{datetime.now(timezone.utc).strftime("%B %d, %Y %H:%M UTC")}</p>
  </div>

  <div class="disclaimer">
    ⚠️ <strong>IMPORTANT:</strong> {DISCLAIMER}
  </div>

  <h2>Case Information</h2>
  <div class="info-grid">
    <div class="info-card"><label>Case Title</label><p>{state.get("case_title", "N/A")}</p></div>
    <div class="info-card"><label>Case ID</label><p>{str(state.get("case_id",""))[:20]}...</p></div>
    <div class="info-card"><label>Pages</label><p>{state.get("page_count", "N/A")}</p></div>
    <div class="info-card"><label>Confidence</label><p><span class="confidence-badge">{confidence:.1%}</span></p></div>
  </div>

  <h2>Executive Summary</h2>
  <p>{state.get("summary", "No summary available.")[:1500]}</p>

  <h2>Key Facts</h2>
  <ul>{facts_html}</ul>

  <h2>AI Recommendation</h2>
  <div class="debate-section">
    <p><strong>Recommendation:</strong> {explainability.get("recommendation", debate.get("final_recommendation", "N/A"))}</p>
    <p style="margin-top:10px"><strong>Confidence:</strong> <span class="confidence-badge">{confidence:.1%}</span></p>
  </div>

  <h2>Multi-Agent Debate</h2>
  <div class="debate-section">
    <h3>⚔️ Prosecution</h3>
    <p>{debate.get("prosecution_argument", "N/A")[:600]}</p>
  </div>
  <div class="debate-section">
    <h3>🛡️ Defense</h3>
    <p>{debate.get("defense_argument", "N/A")[:600]}</p>
  </div>
  <div class="debate-section">
    <h3>⚖️ Judge Assessment</h3>
    <p>{debate.get("judge_assessment", "N/A")[:600]}</p>
  </div>

  <h2>Extracted Legal Entities</h2>
  <table>
    <tr><th>Entity Type</th><th>Values</th></tr>
    {entities_html}
  </table>

  <div class="footer">
    <p>Generated by LexOrch-KG v1.0.0 | AI Decision Support System</p>
    <p style="color:#e53e3e;margin-top:8px">{DISCLAIMER}</p>
  </div>
</div>
</body>
</html>"""
